### PR TITLE
Refactor rebase on master

### PR DESCRIPTION
**Pull request by rpignolet**
#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by gboutry — APPROVED** [review]

**Review by Nuttymoon — APPROVED** [review]

**Comment by leopaul36** [comment]
I think we should upgrade the `tdp-vagrant`'s submodule to use generic/centos7 I'm getting the Postrges installation issue:

```
TASK [tosit.tdp_prerequisites.postgresql : Install PostgreSQL public repo RPM] ***************************************************************************************************************************************************************
fatal: [master-03]: FAILED! => changed=false 
  msg: 'Failure downloading https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm, Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>'
```

**Comment by gboutry** [comment]
> I think we should upgrade the `tdp-vagrant`'s submodule to use generic/centos7 I'm getting the Postrges installation issue:
> 
> ```
> TASK [tosit.tdp_prerequisites.postgresql : Install PostgreSQL public repo RPM] ***************************************************************************************************************************************************************
> fatal: [master-03]: FAILED! => changed=false 
>   msg: 'Failure downloading https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm, Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>'
> ```

https://github.com/TOSIT-IO/tdp-vagrant/blob/master/vagrant.yml

It should already be the case. Check if you do not have a rogue vagrant.yml at tdp-getting-started root

**Comment by leopaul36** [comment]
FYI I came across this one while deploying https://github.com/TOSIT-IO/tdp-collection-extras/issues/69

Not related to the refactor, continuing my tests...

**Comment by leopaul36** [comment]
> > > I think we should upgrade the `tdp-vagrant`'s submodule to use generic/centos7 I'm getting the Postrges installation issue:
> > > ```
> > > TASK [tosit.tdp_prerequisites.postgresql : Install PostgreSQL public repo RPM] ***************************************************************************************************************************************************************
> > > fatal: [master-03]: FAILED! => changed=false 
> > >   msg: 'Failure downloading https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm, Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>'
> > > ```
> > 
> > 
> > https://github.com/TOSIT-IO/tdp-vagrant/blob/master/vagrant.yml
> > It should already be the case. Check if you do not have a rogue vagrant.yml at tdp-getting-started root
> 
> By upgrade I meant the submodule to `tdp-vagrant` in `refactor-rebase`, it's still targeting the previous commit `9489297dbc93162ee5d2f41537c22a13d139b801` instead of latest `ae8caa9e1018ec39e918842203940c554160d533`:
> 
> image

Made a PR: https://github.com/TOSIT-IO/tdp-getting-started/pull/198

**Review by leopaul36 — APPROVED** [review]
Fresh install ran smoothly! Good job on this big refactor @rpignolet

**Pull request merged**
