### PR TITLE
fix: bump submodules

### LINKED ISSUE #285: Update submodule revisions
tdp deploy fails using the current submodule revisions.

### PR DESCRIPTION
**Pull request by mohamedoud**
#### Which issue(s) this PR fixes

Fixes #285 

#### Additional comments

- **tdp-server:** Rebased to the latest commit from the master branch.
- **tdp-prerequisites:** Rebased to the latest commit before upgrading to ansible 2.15 (d67f0ae).
- **tdp-collection:** Rebased to the latest commit before upgrading to ansible 2.15 (d93568c).
- **tdp-extra:** Rebased to the latest commit before upgrading to ansible 2.15 (e50f4fe). 
- **tdp-observability:** Rebased to the latest commit before upgrading to ansible 2.15 (eaed386).
- **tdp-ui:** Rebased to the latest commit from the 0.1 tag.

Tested with a fresh deployment.

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Review by rpignolet — APPROVED** [review]

**Review by gonzaloetjo — APPROVED** [review]
Approved, but we should wait for https://github.com/TOSIT-IO/tdp-getting-started/issues/282

**Comment by rpignolet** [comment]
> Approved, but we should wait for #282

This PR is needed to tag a version of the getting started before ansible 2.15.

**Comment by gonzaloetjo** [comment]
> This PR is needed to tag a version of the getting started before ansible 2.15.

Yep, you are right, thought it was including it.

**Comment by PACordonnier** [comment]
I think we can bump tdp-lib as well to the 0.1 release. It's quite old and still uses the old CLI (tdp deploy) so no need to update the README :D

**Pull request merged**
