### PR TITLE
Adding Apache NiFi

### LINKED ISSUE #86: Adding Apache NiFi 1.16.1 .zip binary release url
context ref: https://github.com/TOSIT-IO/TDP/issues/15

Here is the first step toward the NiFi integration.
Ansible playbooks will be PR soon

### PR DESCRIPTION
**Pull request by pm-McFly**
Fixes #86 

--

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by jbonofre** [comment]
Thanks. I think it would be better to store all changes on the forks (like you do on NiFi) in TDP repo. It would help to have a central place for the changes. I will talk to Édouard and the team about that.

**Comment by leopaul36** [comment]
Waiting for the changes requested

**Review by jbonofre — APPROVED** [review]
It looks good to me to show Apache NiFi there as it's a regular version tested with TDP. Thanks.

**Comment by leopaul36** [comment]
I have reverted this it's nowhere near as ready to being ready to be merged. The pre-requisites stated https://github.com/Linagora-BigData/nifi-TDP/issues/1 should be done first.

@jbonofre please do not merge anything without at least two approvals by core members of the TDP team.

**Comment by leopaul36** [comment]
@pm-McFly keeping this closed for now. Please do another PR once the changes requested in https://github.com/Linagora-BigData/nifi-TDP/issues/1 are ready on your side 👍

**Comment by jbonofre** [comment]
@leopaul36 sorry about that, the PR looks good to me (I requested to change to use the Apache version as it works fine with TDP).
I think we have to work on:
1. CONTRIBUTING.md with the process
2. mailing lists, especially dev one, to be aligned in the governance/process

It's urgent as else it would impact/delay the third party contributions ;)

Sorry again, and let's work together on that one. Thanks !

**Comment by pm-McFly** [comment]
Following the discussion with @jbonofre, the NiFi download links now point to the official Apache Foundation builds. This is because the version of NiFi we were offering was nothing more than a retag.

Given the absence of external dependencies in NiFi, there is no need for such a version.

Ansible playbooks will follow ASAP.<br />
Improvements in the TDP(main) documentation can be found here:

- https://github.com/TOSIT-IO/TDP/pull/20

**Pull request merged**
